DROP TABLE IF EXISTS Characteristics;
  
CREATE SEQUENCE Characteristics_seq;

CREATE TABLE Characteristics (
id INTEGER NULL DEFAULT NEXTVAL ('Characteristics_seq') DEFAULT NULL,
id_size INTEGER NULL DEFAULT NULL,
id_width INTEGER NULL DEFAULT NULL,
id_comfort INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS metadata;
  
CREATE SEQUENCE metadata_seq;

CREATE TABLE metadata (
id INTEGER NULL DEFAULT NEXTVAL ('metadata_seq') DEFAULT NULL,
product_id INTEGER NULL DEFAULT NULL,
id_ratings INTEGER NULL DEFAULT NULL,
id_recommend INTEGER NULL DEFAULT NULL,
id_Characteristics INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);



DROP TABLE IF EXISTS photos;
  
CREATE SEQUENCE photos_seq;

CREATE TABLE photos (
id INTEGER NULL DEFAULT NEXTVAL ('photos_seq') DEFAULT NULL,
id_photo INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);



DROP TABLE IF EXISTS Review;
  
CREATE SEQUENCE Review_seq;

CREATE TABLE Review (
id INTEGER NULL DEFAULT NEXTVAL ('Review_seq') DEFAULT NULL,
product_id INTEGER NULL DEFAULT NULL,
page INTEGER NULL DEFAULT 0,
rating INTEGER NULL DEFAULT NULL,
summary MEDIUMTEXT NULL DEFAULT NULL,
recommend SMALLINT NULL DEFAULT 0,
response MEDIUMTEXT NULL DEFAULT NULL,
body MEDIUMTEXT NULL DEFAULT NULL,
date TIMESTAMP(0) NULL DEFAULT NULL,
reviewer_name MEDIUMTEXT NULL DEFAULT NULL,
helpfulness INTEGER NULL DEFAULT NULL,
email MEDIUMTEXT NULL DEFAULT NULL,
id_photos INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);


DROP TABLE IF EXISTS size;
  
CREATE SEQUENCE size_seq;

CREATE TABLE size (
id INTEGER NULL DEFAULT NEXTVAL ('size_seq') DEFAULT NULL,
value MEDIUMTEXT NULL DEFAULT NULL,
PRIMARY KEY (id)
);



DROP TABLE IF EXISTS width;
  
CREATE SEQUENCE width_seq;

CREATE TABLE width (
id INTEGER NULL DEFAULT NEXTVAL ('width_seq') DEFAULT NULL,
value MEDIUMTEXT NULL DEFAULT NULL,
PRIMARY KEY (id)
);


DROP TABLE IF EXISTS comfort;
  
CREATE SEQUENCE comfort_seq;

CREATE TABLE comfort (
id INTEGER NULL DEFAULT NEXTVAL ('comfort_seq') DEFAULT NULL,
value MEDIUMTEXT NULL DEFAULT NULL,
PRIMARY KEY (id)
);


DROP TABLE IF EXISTS ratings;
  
CREATE SEQUENCE ratings_seq;

CREATE TABLE ratings (
id INTEGER NULL DEFAULT NEXTVAL ('ratings_seq') DEFAULT NULL,
0 INTEGER NULL DEFAULT NULL,
1 INTEGER NULL DEFAULT NULL,
2 INTEGER NULL DEFAULT NULL,
3 INTEGER NULL DEFAULT NULL,
4 INTEGER NULL DEFAULT NULL,
5 INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS recommend;
  
CREATE SEQUENCE recommend_seq;

CREATE TABLE recommend (
id INTEGER NULL DEFAULT NEXTVAL ('recommend_seq') DEFAULT NULL,
false INTEGER NULL DEFAULT NULL,
true INTEGER NULL DEFAULT NULL,
PRIMARY KEY (id)
);


DROP TABLE IF EXISTS photo;
  
CREATE SEQUENCE photo_seq;

CREATE TABLE photo (
id INTEGER NULL DEFAULT NEXTVAL ('photo_seq') DEFAULT NULL,
thumbnail_url MEDIUMTEXT NULL DEFAULT NULL,
url MEDIUMTEXT NULL DEFAULT NULL,
PRIMARY KEY (id)
);

ALTER TABLE Characteristics ADD FOREIGN KEY (id_size) REFERENCES size (id);
ALTER TABLE Characteristics ADD FOREIGN KEY (id_width) REFERENCES width (id);
ALTER TABLE Characteristics ADD FOREIGN KEY (id_comfort) REFERENCES comfort (id);
ALTER TABLE metadata ADD FOREIGN KEY (id_ratings) REFERENCES ratings (id);
ALTER TABLE metadata ADD FOREIGN KEY (id_recommend) REFERENCES recommend (id);
ALTER TABLE metadata ADD FOREIGN KEY (id_Characteristics) REFERENCES Characteristics (id);
ALTER TABLE photos ADD FOREIGN KEY (id_photo) REFERENCES photo (id);
ALTER TABLE Review ADD FOREIGN KEY (id_photos) REFERENCES photos (id); 

ALTER TABLE Characteristics ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE metadata ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE photos ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE Review ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE size ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE width ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE comfort ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE ratings ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE recommend ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE photo ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;